version: "3.9"

services:
  back__nginx:
    image: nginx:latest
    container_name: back__nginx
    ports:
      - ${PHP_NGINX_PORT}:80
      - "3306:3306"
    volumes:
      - ./docker/back/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./back:/var/www/html
    links:
      - back__php
    working_dir: /var/www/html

  back__php:
    build: docker/back/php
    container_name: back__php
    expose:
      - 9000
    volumes:
      - ./back:/var/www/html
      - ./docker/back/php/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    depends_on:
      - back__db
    working_dir: /var/www/html

  back__db:
    image: mariadb:10.5
    container_name: back__db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    ports:
      - "33306:3306"

  front__node:
    image: node:16
    container_name: front__node
    volumes:
      - ./front:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["tail", "-f", "/dev/null"]

  front__nginx:
    image: nginx:latest
    container_name: front__nginx
    ports:
      - ${NODE_NGINX_PORT}:80
    links:
      - front__node
    working_dir: /usr/share/nginx/html
    volumes:
      - ./docker/front/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./front:/var/www/html

volumes:
  db:
